# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf18ecfc1b599dde640594678541b141bc08f40d334a52331a49e3a05c1d968769533dbc83b11cc20dc3906eef206138a5a4a8e951867efd9596f50627c113e9

test:
  secret_key_base: adefc67c39c7bd23facb36c14b03f49ef1e8234f38ce2d676205f5595c1f112d4d0385475830976a5650925d66ec65e36003417fcdd57ba6a0190b68a7a8bcc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
